[build]
  command = 'yarn build'
  publish = 'packages/ui/build'

[functions]
  directory = 'packages/api/functions'
  included_files = [
    'packages/common/config.json',
    'packages/common/src/*.js',
  ]

[[redirects]]
  from = '/sites'
  to = '/.netlify/functions/sites'
  status = 200
