[build]
  command = 'yarn build' 
  publish = 'packages/ui/build'

[functions]
  directory = 'packages/api/functions/'
  included_files = [
    'packages/common/*',
  ]

[[redirects]]
  from = '/sites'
  to = '/.netlify/functions/sites'
  status = 200

[[redirects]]
  from = '/site'
  to = '/.netlify/functions/site'
  status = 200

[[redirects]]
  from = '/*'
  to = '/'
  status = 200

